In [5]:
## basic
import glob
import os
import pandas as pd

In [20]:
df = pd.read_csv(r'/Users/donghyunkim/Library/CloudStorage/GoogleDrive-dannykim0195@gmail.com/My Drive/korean_delivery/busan_2305.csv', encoding='EUC-KR')
df

,crym,admd_c,ana_mgpo_nm,ana_ccd_nm,admd_nm,dayofweek,sl_am,sl_ct
0,202305,2611051000,부산광역시,중구,중앙동,Fri,1440630,64
1,202305,2611051000,부산광역시,중구,중앙동,Mon,2275600,102
2,202305,2611051000,부산광역시,중구,중앙동,Sat,2007800,89
3,202305,2611051000,부산광역시,중구,중앙동,Sun,2610140,111
4,202305,2611051000,부산광역시,중구,중앙동,Thu,2060965,90
...,...,...,...,...,...,...,...,...
1390,202305,2671033000,부산광역시,기장군,철마면,Sat,1128270,38
1391,202305,2671033000,부산광역시,기장군,철마면,Sun,1802470,61
1392,202305,2671033000,부산광역시,기장군,철마면,Thu,369400,14
1393,202305,2671033000,부산광역시,기장군,철마면,Tue,488170,17
1394,202305,2671033000,부산광역시,기장군,철마면,Wed,576500,19

In [29]:
# the path to your csv file directory
mycsvdir = '/Users/donghyunkim/Library/CloudStorage/GoogleDrive-dannykim0195@gmail.com/My Drive/korean_delivery'

# get all the csv files in that directory (assuming they have the extension .csv)
csvfiles = glob.glob(os.path.join(mycsvdir, '*.csv'))

# loop through the files and read them in with pandas
dataframes = []  # a list to hold all the individual pandas DataFrames
for csvfile in csvfiles:
    df = pd.read_csv(csvfile, encoding='cp949')
    dataframes.append(df)

# concatenate them all together
result = pd.concat(dataframes, ignore_index=True)
result.rename(columns={'crym': '기준년월', 'admd_c': '행정동코드', 'ana_mgpo_nm': '광역시도명', 'ana_ccd_nm': '시군구명', 'admd_nm': '행정동명', 'dayofweek': '요일', 'time_interval': '시간대', 'sl_am': '이용금액', 'sl_ct': '이용건수'  }, inplace=True)

result
# print out to a new csv file
## result.to_csv('all.csv')

,기준년월,행정동코드,광역시도명,시군구명,행정동명,요일,이용금액,이용건수,Unnamed: 0,cdw,시간대,tco_btc
0,202306,4711125000,경상북도,포항시 남구,구룡포읍,Fri,87000.0,3,NaN,NaN,NaN,NaN
1,202306,4711125000,경상북도,포항시 남구,구룡포읍,Sun,178630.0,7,NaN,NaN,NaN,NaN
2,202306,4711125000,경상북도,포항시 남구,구룡포읍,Thu,60900.0,3,NaN,NaN,NaN,NaN
3,202306,4711125000,경상북도,포항시 남구,구룡포읍,Tue,98800.0,3,NaN,NaN,NaN,NaN
4,202306,4711125300,경상북도,포항시 남구,연일읍,Fri,4540547.0,161,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
992530,202304,4283032000,강원도,양양군,손양면,Sun,166100.0,6,NaN,NaN,NaN,NaN
992531,202304,4283032000,강원도,양양군,손양면,Thu,78400.0,3,NaN,NaN,NaN,NaN
992532,202304,4283032000,강원도,양양군,손양면,Tue,59700.0,3,NaN,NaN,NaN,NaN
992533,202304,4283035000,강원도,양양군,강현면,Fri,213400.0,10,NaN,NaN,NaN,NaN
992534,202304,4283035000,강원도,양양군,강현면,Wed,50750.0,3,NaN,NaN,NaN,NaN

In [43]:
## check null value 
nan_cols = [i for i in result.columns if result[i].isnull().any()]
nan_cols

['요일', 'Unnamed: 0', 'cdw', '시간대', 'tco_btc']

In [118]:
def get_df_null(df):
    
    list_of_dfs = []
    for col in col_list:
        df_notna=df[df[col].notna()]
        df_group = df_notna.groupby(['기준년월','광역시도명'])['시군구명'].count()
        list_of_dfs.append(df_group)
    print(list_of_dfs)
get_df_null(result,nan_cols)

[기준년월    광역시도명
202209  강원도         9394
        경기도        57219
        경상남도       17958
        경상북도       13999
        광주광역시       9840
                   ...
202308  전라남도         609
        전라북도         640
        제주특별자치도      277
        충청남도         628
        충청북도         550
Name: 시군구명, Length: 174, dtype: int64, 기준년월    광역시도명
202210  광주광역시     6888
        대구광역시    11349
        대전광역시     3747
        부산광역시    18801
        인천광역시    11757
202211  광주광역시     6870
        대구광역시    11136
        대전광역시     6273
        부산광역시    18581
        인천광역시    11637
202212  광주광역시     6713
        대구광역시    11686
        대전광역시     6552
        부산광역시    19167
        인천광역시    11960
202301  광주광역시     6978
        대구광역시    11582
        대전광역시     6519
        부산광역시    19110
        인천광역시    11906
202302  광주광역시     6781
        대구광역시    11122
        대전광역시     6420
        부산광역시    18494
        인천광역시    11642
202303  광주광역시     6790
        대구광역시    11041
        대전광역시     6389
        부산광역시    18492
        인천광역시    11563
Name: 시군구명, dtype: int64, 기준년월    광역시도명
202210  광주광역시     6888
        대구광역시    11349
        대전광역시     3747
        부산광역시    18801
        인천광역시    11757
202211  광주광역시     6870
        대구광역시    11136
        대전광역시     6273
        부산광역시    18581
        인천광역시    11637
202212  광주광역시     6713
        대구광역시    11686
        대전광역시     6552
        부산광역시    19167
        인천광역시    11960
202301  광주광역시     6978
        대구광역시    11582
        대전광역시     6519
        부산광역시    19110
        인천광역시    11906
202302  광주광역시     6781
        대구광역시    11122
        대전광역시     6420
        부산광역시    18494
        인천광역시    11642
202303  광주광역시     6790
        대구광역시    11041
        대전광역시     6389
        부산광역시    18492
        인천광역시    11563
Name: 시군구명, dtype: int64, 기준년월    광역시도명
202209  강원도       9394
        경기도      57219
        경상남도     17958
        경상북도     13999
        광주광역시     9840
                 ...
202303  광주광역시     6790
        대구광역시    11041
        대전광역시     6389
        부산광역시    18492
        인천광역시    11563
Name: 시군구명, Length: 70, dtype: int64, 기준년월    광역시도명
202210  대전광역시    3747
Name: 시군구명, dtype: int64]

In [122]:
test1 = result[result['tco_btc'].notna()]
test1.groupby(['기준년월','광역시도명'])['시군구명'].count()

##test[].groupby('시간대').count()

기준년월    광역시도명
202210  대전광역시    3747
Name: 시군구명, dtype: int64

In [33]:
test = result[result['cdw'].notna()]
test

,기준년월,행정동코드,광역시도명,시군구명,행정동명,요일,이용금액,이용건수,Unnamed: 0,cdw,시간대,tco_btc
3858,202211,2644053000,부산광역시,강서구,강동동,NaN,84000.0,4,1.0,FRI,17.0,NaN
3859,202211,2644053000,부산광역시,강서구,강동동,NaN,94000.0,3,2.0,MON,15.0,NaN
3860,202211,2644056000,부산광역시,강서구,녹산동,NaN,485000.0,23,3.0,FRI,10.0,NaN
3861,202211,2644056000,부산광역시,강서구,녹산동,NaN,578000.0,20,4.0,FRI,22.0,NaN
3862,202211,2644056000,부산광역시,강서구,녹산동,NaN,275000.0,10,5.0,FRI,23.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
991908,202302,2811062800,인천광역시,중구,운서동,NaN,26000.0,3,11638.0,WED,8.0,NaN
991909,202302,2811062800,인천광역시,중구,운서동,NaN,322000.0,12,11639.0,WED,22.0,NaN
991910,202302,2811057000,인천광역시,중구,율목동,NaN,116000.0,4,11640.0,MON,12.0,NaN
991911,202302,2811057000,인천광역시,중구,율목동,NaN,162000.0,4,11641.0,SAT,20.0,NaN
991912,202302,2811057000,인천광역시,중구,율목동,NaN,65000.0,3,11642.0,THU,12.0,NaN

In [27]:
test

,crym,admd_c,ana_mgpo_nm,ana_ccd_nm,admd_nm,dayofweek,sl_am,sl_ct,Unnamed: 0,cdw,time_interval,tco_btc
3858,202211,2644053000,부산광역시,강서구,강동동,NaN,84000.0,4,1.0,FRI,17.0,NaN
3859,202211,2644053000,부산광역시,강서구,강동동,NaN,94000.0,3,2.0,MON,15.0,NaN
3860,202211,2644056000,부산광역시,강서구,녹산동,NaN,485000.0,23,3.0,FRI,10.0,NaN
3861,202211,2644056000,부산광역시,강서구,녹산동,NaN,578000.0,20,4.0,FRI,22.0,NaN
3862,202211,2644056000,부산광역시,강서구,녹산동,NaN,275000.0,10,5.0,FRI,23.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
991908,202302,2811062800,인천광역시,중구,운서동,NaN,26000.0,3,11638.0,WED,8.0,NaN
991909,202302,2811062800,인천광역시,중구,운서동,NaN,322000.0,12,11639.0,WED,22.0,NaN
991910,202302,2811057000,인천광역시,중구,율목동,NaN,116000.0,4,11640.0,MON,12.0,NaN
991911,202302,2811057000,인천광역시,중구,율목동,NaN,162000.0,4,11641.0,SAT,20.0,NaN
991912,202302,2811057000,인천광역시,중구,율목동,NaN,65000.0,3,11642.0,THU,12.0,NaN

In [15]:
df = pd.read_csv(r'busan_2305.csv', encoding='EUC-KR')

FileNotFoundError: [Errno 2] No such file or directory: 'busan_2305.csv'

In [3]:
df

,Unnamed: 0,crym,ana_mgpo_nm,ana_ccd_nm,admd_nm,admd_c,cdw,time_interval,sl_am,sl_ct
0,1,202210,부산광역시,강서구,가덕도동,2644058000,FRI,16,84000.0,3
1,2,202210,부산광역시,강서구,가덕도동,2644058000,MON,18,84000.0,4
2,3,202210,부산광역시,강서구,가덕도동,2644058000,SUN,19,94000.0,4
3,4,202210,부산광역시,강서구,가락동,2644055000,MON,17,63000.0,3
4,5,202210,부산광역시,강서구,가락동,2644055000,SAT,19,89000.0,4
...,...,...,...,...,...,...,...,...,...,...
18796,18797,202210,부산광역시,해운대구,중2동,2635054000,WED,10,167000.0,7
18797,18798,202210,부산광역시,해운대구,중2동,2635054000,WED,13,260000.0,14
18798,18799,202210,부산광역시,해운대구,중2동,2635054000,WED,17,697000.0,21
18799,18800,202210,부산광역시,해운대구,중2동,2635054000,WED,19,446000.0,20
18800,18801,202210,부산광역시,해운대구,중2동,2635054000,WED,23,133000.0,6

In [4]:
df = pd.read_csv(r'busan_2304.csv', encoding='EUC-KR')

FileNotFoundError: [Errno 2] No such file or directory: 'busan_2304.csv'